/**
 * Seed initial roles from role-config.ts into the database
 * 
 * This script populates the RoleConfiguration table with the default roles
 * defined in src/lib/role-config.ts
 * 
 * Run: npx tsx scripts/seed-roles.ts
 */

import { PrismaClient } from '@prisma/client'
import { ROLE_CONFIG } from '../src/lib/role-config'

const prisma = new PrismaClient()

async function seedRoles() {
  try {
    console.log('🌱 Seeding roles into database...\n')

    let created = 0
    let updated = 0
    let skipped = 0

    for (const [roleKey, config] of Object.entries(ROLE_CONFIG)) {
      const existing = await prisma.roleConfiguration.findUnique({
        where: { roleKey },
      })

      if (existing) {
        // Update existing role to match current config
        await prisma.roleConfiguration.update({
          where: { roleKey },
          data: {
            label: config.label,
            abbreviation: config.abbreviation,
            bgColor: config.bgColor,
            textColor: config.textColor,
            borderColor: config.borderColor,
            priority: config.priority,
            allowMultiple: config.allowMultiple,
            maxAssignments: config.maxAssignments,
            updatedAt: new Date(),
          },
        })
        updated++
        console.log(`  ✅ Updated: ${config.label} (${roleKey})`)
      } else {
        // Create new role
        await prisma.roleConfiguration.create({
          data: {
            roleKey,
            label: config.label,
            abbreviation: config.abbreviation,
            bgColor: config.bgColor,
            textColor: config.textColor,
            borderColor: config.borderColor,
            priority: config.priority,
            allowMultiple: config.allowMultiple,
            maxAssignments: config.maxAssignments,
            isActive: true,
            // updatedAt is auto-generated by Prisma
          },
        })
        created++
        console.log(`  ✨ Created: ${config.label} (${roleKey})`)
      }
    }

    console.log(`\n📊 Summary:`)
    console.log(`   Created: ${created}`)
    console.log(`   Updated: ${updated}`)
    console.log(`   Skipped: ${skipped}`)
    console.log(`\n✅ Role seeding complete!`)

    await prisma.$disconnect()
  } catch (error: any) {
    console.error('❌ Error seeding roles:', error.message)
    await prisma.$disconnect()
    process.exit(1)
  }
}

seedRoles()

